[group:redis]
programs=redis

[program:redis-server]
command=/usr/bin/redis-server /workspace/conf/redis.conf --daemonize no  # 这里已经定义了 redis 的启动命令
autostart=true  # 容器启动时自动启动 redis
priority=1
autorestart=true  # 如果 redis 意外退出，自动重启
stderr_logfile=/var/tmp/redis.err.log
stdout_logfile=/var/tmp/redis.out.log
